import { scheduleRepository } from "./data/supabaseScheduleRepository.js";

export const fetchMonthlyLeavePlans = (...args) => scheduleRepository.fetchMonthlyLeavePlans(...args);
export const fetchTemporarySupportSummary = (...args) => scheduleRepository.fetchTemporarySupportSummary(...args);
export const fetchStaffingDemandRules = (...args) => scheduleRepository.fetchStaffingDemandRules(...args);
export const upsertMonthlyLeavePlan = (...args) => scheduleRepository.upsertMonthlyLeavePlan(...args);
export const upsertMonthlyLeavePlans = (...args) => scheduleRepository.upsertMonthlyLeavePlans(...args);
export const fetchMonthlyScheduleControl = (...args) => scheduleRepository.fetchMonthlyScheduleControl(...args);
export const confirmMonthlySchedule = (...args) => scheduleRepository.confirmMonthlySchedule(...args);
export const unlockMonthlySchedule = (...args) => scheduleRepository.unlockMonthlySchedule(...args);
export const submitMonthlyScheduleChangeRequest = (...args) => scheduleRepository.submitMonthlyScheduleChangeRequest(...args);
export const reviewMonthlyScheduleChangeRequest = (...args) => scheduleRepository.reviewMonthlyScheduleChangeRequest(...args);
export const submitSupportShiftRequest = (...args) => scheduleRepository.submitSupportShiftRequest(...args);
export const reviewSupportShiftRequest = (...args) => scheduleRepository.reviewSupportShiftRequest(...args);
export const setWorkforceRolloutMode = (...args) => scheduleRepository.setWorkforceRolloutMode(...args);
export const fetchPersonalScheduleLinks = (...args) => scheduleRepository.fetchPersonalScheduleLinks(...args);
export const issuePersonalScheduleLink = (...args) => scheduleRepository.issuePersonalScheduleLink(...args);
export const revokePersonalScheduleLink = (...args) => scheduleRepository.revokePersonalScheduleLink(...args);
export const fetchPersonalScheduleByToken = (...args) => scheduleRepository.fetchPersonalScheduleByToken(...args);
export const fetchDailyStaffShifts = (...args) => scheduleRepository.fetchDailyStaffShifts(...args);
export const upsertDailyStaffShift = (...args) => scheduleRepository.upsertDailyStaffShift(...args);
export const deleteDailyStaffShift = (...args) => scheduleRepository.deleteDailyStaffShift(...args);
export const fetchStandardShiftTemplates = (...args) => scheduleRepository.fetchStandardShiftTemplates(...args);
export const upsertStandardShiftTemplate = (...args) => scheduleRepository.upsertStandardShiftTemplate(...args);
export const archiveStandardShiftTemplate = (...args) => scheduleRepository.archiveStandardShiftTemplate(...args);
