export {
  MODULE_GROUPS,
  ROLE_LABELS,
  appViewForRole,
  canAccessModule,
  canEditMonthlyTargets,
  canExportRole,
  canManageDailyReportData,
  canConfirmDailyReports,
  canManageSecurity,
  defaultModuleForRole,
  modulesForRole,
  profileRole,
  visibleViewModesForRole,
} from "./domain/roleAccess.js";
