-- Integration verification: every test order and event rolls back.
begin;
do $$
declare
 receiver_id uuid; sender_id uuid; outsider_id uuid; hq_id uuid; pid uuid;
 r jsonb; v jsonb; cmd jsonb; rid uuid:=gen_random_uuid(); c uuid:=gen_random_uuid();
 caught boolean; initial_count bigint; audit_count bigint;
begin
 select p.id into receiver_id from public.profiles p join public.stores s on s.id=p.store_id where s.store_code='S01' and p.role='store_manager' and p.is_active limit 1;
 select p.id into sender_id from public.profiles p join public.stores s on s.id=p.store_id where s.store_code='S02' and p.role='store_manager' and p.is_active limit 1;
 select p.id into outsider_id from public.profiles p join public.stores s on s.id=p.store_id where s.store_code='S03' and p.role='store_manager' and p.is_active limit 1;
 select id into hq_id from public.profiles where role='coo' and is_active limit 1;
 if receiver_id is null or sender_id is null or outsider_id is null or hq_id is null then raise exception 'Test actors missing'; end if;
 select id into pid from ops_transfer_private.products where code='TR-MEAT-W7';
 select count(*) into initial_count from ops_transfer_private.requests;
 perform set_config('request.jwt.claim.sub',receiver_id::text,true);
 v := public.ops_transfer_api('bootstrap');
 if v->'actor'->>'store'<>'S01' or jsonb_array_length(v->'products')<70 then raise exception 'bootstrap failed'; end if;
 cmd := jsonb_build_object('id',rid,'command_id',c,'receiver','S01','sender','S02','date','2026-09-09','lines',jsonb_build_array(jsonb_build_object('product_id',pid,'quantity',2,'unit','箱')));
 r := public.ops_transfer_api('create',cmd);
 v := public.ops_transfer_api('create',cmd);
 if r<>v or (select count(*) from ops_transfer_private.requests)<>initial_count+1 then raise exception 'idempotency failed'; end if;
 caught:=false;
 begin perform public.ops_transfer_api('create',cmd||jsonb_build_object('id',gen_random_uuid(),'command_id',gen_random_uuid(),'receiver','S03')); exception when others then caught:=true; end;
 if not caught then raise exception 'receiver scope bypass'; end if;
 caught:=false;
 begin perform public.ops_transfer_api('create',cmd||jsonb_build_object('id',gen_random_uuid(),'command_id',gen_random_uuid(),'lines',jsonb_build_array(jsonb_build_object('product_id',pid,'quantity',2,'unit','件')))); exception when others then caught:=true; end;
 if not caught then raise exception 'unit validation bypass'; end if;
 caught:=false;
 begin perform public.ops_transfer_api('ship',jsonb_build_object('id',rid,'version',1,'command_id',gen_random_uuid(),'lines',cmd->'lines')); exception when others then caught:=true; end;
 if not caught then raise exception 'receiver shipped without permission'; end if;
 perform set_config('request.jwt.claim.sub',outsider_id::text,true);
 caught:=false;
 begin perform public.ops_transfer_api('detail',jsonb_build_object('id',rid)); exception when others then caught:=true; end;
 if not caught then raise exception 'unrelated store reads detail'; end if;
 if exists(select 1 from jsonb_array_elements(public.ops_transfer_api('list')) x where x->>'id'=rid::text) then raise exception 'unrelated store reads list'; end if;
 perform set_config('request.jwt.claim.sub',sender_id::text,true);
 r:=public.ops_transfer_api('ship',jsonb_build_object('id',rid,'version',1,'command_id',gen_random_uuid(),'lines',cmd->'lines'));
 if r->>'status'<>'shipped' then raise exception 'ship failed'; end if;
 caught:=false;
 begin perform public.ops_transfer_api('cancel',jsonb_build_object('id',rid,'version',1,'command_id',gen_random_uuid(),'reason','stale')); exception when others then caught:=true; end;
 if not caught then raise exception 'stale write accepted'; end if;
 perform set_config('request.jwt.claim.sub',receiver_id::text,true);
 r:=public.ops_transfer_api('receive',jsonb_build_object('id',rid,'version',2,'command_id',gen_random_uuid(),'reason','少收到一箱','lines',jsonb_build_array(jsonb_build_object('product_id',pid,'quantity',1))));
 if r->>'status'<>'disputed' then raise exception 'difference closed silently'; end if;
 perform set_config('request.jwt.claim.sub',sender_id::text,true);
 r:=public.ops_transfer_api('resolve',jsonb_build_object('id',rid,'version',3,'command_id',gen_random_uuid(),'reason','以實收一箱結案，未送部分不補送'));
 r:=public.ops_transfer_api('ack_sender',jsonb_build_object('id',rid,'version',4,'command_id',gen_random_uuid()));
 if r->>'status'<>'disputed' then raise exception 'single party closed difference'; end if;
 perform set_config('request.jwt.claim.sub',receiver_id::text,true);
 r:=public.ops_transfer_api('ack_receiver',jsonb_build_object('id',rid,'version',5,'command_id',gen_random_uuid()));
 if r->>'status'<>'completed' then raise exception 'resolution failed'; end if;
 caught:=false;
 begin perform public.ops_transfer_api('cancel',jsonb_build_object('id',rid,'version',6,'command_id',gen_random_uuid(),'reason','cannot delete')); exception when others then caught:=true; end;
 if not caught then raise exception 'completed cancelled'; end if;
 select count(*) into audit_count from ops_transfer_private.events where request_id=rid;
 if audit_count<>6 then raise exception 'expected 6 audit events, got %',audit_count; end if;
 -- Normal receipt and cancellation paths.
 rid:=gen_random_uuid(); cmd:=cmd||jsonb_build_object('id',rid,'command_id',gen_random_uuid());
 r:=public.ops_transfer_api('create',cmd);
 perform set_config('request.jwt.claim.sub',sender_id::text,true);
 r:=public.ops_transfer_api('ship',jsonb_build_object('id',rid,'version',1,'command_id',gen_random_uuid(),'lines',cmd->'lines'));
 perform set_config('request.jwt.claim.sub',receiver_id::text,true);
 r:=public.ops_transfer_api('receive',jsonb_build_object('id',rid,'version',2,'command_id',gen_random_uuid(),'lines',cmd->'lines'));
 if r->>'status'<>'completed' then raise exception 'normal receipt failed'; end if;
 rid:=gen_random_uuid(); cmd:=cmd||jsonb_build_object('id',rid,'command_id',gen_random_uuid());
 r:=public.ops_transfer_api('create',cmd);
 r:=public.ops_transfer_api('cancel',jsonb_build_object('id',rid,'version',1,'command_id',gen_random_uuid(),'reason','不需調貨'));
 if r->>'status'<>'cancelled' then raise exception 'cancel failed'; end if;
 perform set_config('request.jwt.claim.sub',hq_id::text,true);
 v:=public.ops_transfer_api('bootstrap');
 if not (v->'actor'->>'is_hq')::boolean then raise exception 'HQ permission failed'; end if;
 select to_jsonb(p) into v from ops_transfer_private.products p where id=pid;
 r:=public.ops_transfer_api('product',v||jsonb_build_object('command_id',gen_random_uuid(),'reason','測試獨立品項異動','name','雞翅測試名稱'));
 if r->>'name'<>'雞翅測試名稱' or jsonb_array_length(public.ops_transfer_product_history(pid))<>1 then raise exception 'product audit failed'; end if;
 if exists(select 1 from ops_transfer_private.requests x,jsonb_array_elements(x.data->'lines') l where l->>'product_id'=pid::text and l->>'name'='雞翅測試名稱') then raise exception 'historical snapshot overwritten'; end if;
 perform set_config('request.jwt.claim.sub',receiver_id::text,true);
 caught:=false;
 begin perform public.ops_transfer_product_history(pid); exception when others then caught:=true; end;
 if not caught then raise exception 'store can read HQ product audits'; end if;
 if has_function_privilege('anon','public.ops_transfer_api(text,jsonb)','execute') then raise exception 'anonymous RPC exposed'; end if;
 if has_schema_privilege('authenticated','ops_transfer_private','usage') then raise exception 'private tables exposed'; end if;
 perform set_config('request.jwt.claim.sub','',true);
 caught:=false;
 begin perform public.ops_transfer_api('bootstrap'); exception when others then caught:=true; end;
 if not caught then raise exception 'anonymous actor accepted'; end if;
end $$;
select 'PASS: scope, units, idempotency, optimistic lock, normal/difference/cancel lifecycle, audit and private grants' as result;
rollback;
