import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { PGlite } from '@electric-sql/pglite';
const id=n=>`00000000-0000-0000-0000-${String(n).padStart(12,'0')}`;
test('HQ and kg migration keeps stores isolated and supports fractional shipping/receipt',async()=>{
 const db=new PGlite(); let count=500;
 const migrate=async name=>db.exec(await readFile(new URL(`../supabase/migrations/${name}.sql`,import.meta.url),'utf8'));
 try {
  await db.exec(`create role anon;create role authenticated;create schema auth;
   create function auth.uid() returns uuid language sql as $$select nullif(current_setting('test.uid',true),'')::uuid$$;
   create table public.stores(id uuid primary key,store_code text,name text,is_active boolean);
   create table public.profiles(id uuid primary key,full_name text,role text,store_id uuid,is_active boolean);
   insert into stores values('${id(1)}','S01','五甲',true),('${id(2)}','S02','凱旋',true),('${id(3)}','S03','武廟',true);
   insert into profiles values('${id(1)}','總部','coo',null,true),('${id(2)}','收貨店','store_manager','${id(2)}',true),('${id(3)}','其他店','store_manager','${id(3)}',true);
   create table public.franchise_order_products(id uuid primary key,product_code text,name text,category text,note text,order_unit text,sort_order int,is_orderable boolean,is_adjustment boolean);
   insert into franchise_order_products values('${id(100)}','W7','雞翅','肉品','','箱',1,true,false),
    ('${id(101)}','SNACK-CUT-SWEET-POTATO-9KG','地瓜','點心','','包',2,true,false),
    ('${id(102)}','BALL','花枝丸','點心','','包',3,true,false);`);
  await migrate('20260909124828_transfer_center');
  await migrate('20260909233801_transfer_add_pork_chop');
  await migrate('20260909234011_transfer_product_store_directions');
  await migrate('20260910053806_transfer_inbox_readonly');
  const before=(await db.query('select * from public.franchise_order_products')).rows;
  await migrate('20260910152954_transfer_decimal_kg_hq_source');
  await migrate('20260910152956_transfer_stock_pickup_note');
  assert.deepEqual((await db.query('select * from public.franchise_order_products')).rows,before);
  assert.equal((await db.query('select count(*) n from public.stores')).rows[0].n,3);
  const user=async n=>db.query("select set_config('test.uid',$1,false)",[id(n)]);
  const call=async(a,p={})=>(await db.query('select public.ops_transfer_api($1,$2) r',[a,JSON.stringify(p)])).rows[0].r;
  const write=(a,p)=>call(a,{...p,command_id:id(count++)});
  await user(2);
  const boot=await call('bootstrap');
  assert.equal(boot.senders[0].code,'HQ');assert.equal(boot.stores.some(s=>s.code==='HQ'),false);
  assert.ok(boot.products.every(p=>p.units.includes('公斤')));
  const prod=boot.products.find(p=>p.code==='TR-W7');
  const payload={id:id(200),sender:'HQ',receiver:'S02',date:'2026-09-10',lines:[{product_id:prod.id,quantity:1.125,unit:'公斤',stock_pickup:true}]};
  const r=await write('create',payload);
  assert.equal(r.data.sender_name,'總部');assert.equal(r.data.lines[0].quantity,1.125);
  assert.equal(r.data.lines[0].unit,'公斤');
  assert.equal(r.data.lines[0].stock_pickup,true);
  const potato=boot.products.find(p=>p.name==='地瓜'), ball=boot.products.find(p=>p.name==='花枝丸');
  await assert.rejects(write('create',{...payload,id:id(202),lines:[{product_id:ball.id,quantity:1,unit:'包',stock_pickup:true}]}),/只有肉類/);
  await assert.rejects(write('create',{...payload,id:id(202),lines:[{product_id:prod.id,quantity:1,unit:'包',stock_pickup:'false'}]}),/須為勾選/);
  const sweet=await write('create',{...payload,id:id(203),lines:[{product_id:potato.id,quantity:0.5,unit:'包',stock_pickup:true}]});
  assert.equal(sweet.data.lines[0].stock_pickup,true);
  await assert.rejects(write('create',{...payload,id:id(201),receiver:'HQ',sender:'S02'}));
  await assert.rejects(write('create',{...payload,id:id(201),lines:[{product_id:prod.id,quantity:0.0001,unit:'公斤'}]}));
  await assert.rejects(write('ship',{id:r.id,version:1,lines:payload.lines}));
  await user(3);await assert.rejects(call('detail',{id:r.id}));
  await user(1);
  const inbox=(await db.query('select public.ops_transfer_inbox() r')).rows[0].r;
  assert.equal(inbox.counts.requested,2);
  const shipped=await write('ship',{id:r.id,version:1,reason:'總部出貨',lines:[{product_id:prod.id,quantity:1.1}]});
  assert.equal(shipped.data.shipped[0].unit,'公斤');
  assert.equal(shipped.data.shipped[0].stock_pickup,true);
  await user(2);
  const received=await write('receive',{id:r.id,version:2,lines:[{product_id:prod.id,quantity:1.1}]});
  assert.equal(received.status,'completed');
  assert.equal(received.data.received[0].quantity,1.1);
  assert.equal(received.data.received[0].stock_pickup,true);
  await user(1);
  const pork=(await call('bootstrap')).products.find(p=>p.code==='TR-MEAT-PORK-CHOP');
  assert.deepEqual(pork.receiver_stores,['S02','S08']);
  assert.deepEqual(pork.sender_stores,['HQ','S01']);
  await write('product',{...pork,reason:'設定',sender_stores:['HQ'],units:['公斤']});
  await assert.rejects(write('product',{...pork,version:pork.version+1,reason:'非法收貨',receiver_stores:['HQ']}));
  assert.equal((await db.query('select count(*) n from ops_transfer_private.catalog_rollouts')).rows[0].n,4);
 } finally {await db.close();}
});
